/** Query param keys used by map share / POI deep links. Keep in sync across encode, parse, and shortener validation. */
export const SHARE_QUERY_PARAM_KEYS = [
	'lat',
	'lng',
	'zoom',
	'dir',
	'progress',
	'unit',
	'baseMap',
	'trailStyle',
	'sections',
	'dark',
	'ruler',
	'pois',
	'weather',
	'radar',
	'distanceMarkers',
	'waymarked',
	'poi',
] as const;
