import { isSafeUrl } from '@/lib/utils';

/**
 * OSM way tags sampled along the CLDT and run-length encoded. Generated by
 * `scripts/enrich-trail-osm.ts` and served at /trail-osm-tags.json. Consumed
 * at runtime by the surface- and SAC-difficulty trail-style color modes.
 */

export type SacScale =
	| 'hiking'
	| 'mountain_hiking'
	| 'demanding_mountain_hiking'
	| 'alpine_hiking'
	| 'demanding_alpine_hiking'
	| 'difficult_alpine_hiking';

export interface TrailOsmTagRun {
	fromKm: number;
	toKm: number;
	surface: string | null;
	highway: string | null;
	sac_scale: SacScale | null;
	mtb_scale: string | null;
}

export interface TrailOsmTagsFile {
	lastUpdated: string;
	totalKm: number;
	sampleStepM?: number;
	runs: TrailOsmTagRun[];
}

/**
 * Coarse surface buckets mapped from the long tail of OSM surface=* values.
 * Drives the surface-color-mode palette so the legend only has 5 entries
 * rather than every conceivable surface tag.
 */
export type SurfaceBucket = 'paved' | 'unpaved' | 'gravel' | 'ground' | 'rock' | 'unknown';

/**
 * Maps an OSM surface=* value to a coarse bucket. Returns 'unknown' for
 * untagged or unrecognized surfaces so the renderer can color them
 * distinctly rather than dropping them. The mapping leans conservative for
 * hikers: anything that's clearly trail (ground / dirt / earth / grass /
 * mud) collapses to 'ground'; track-like surfaces (gravel / compacted /
 * fine_gravel / pebblestone) collapse to 'gravel'; rock / scree / sand
 * stay as 'rock' so dangerous-footing surfaces are flagged distinctly.
 */
export function bucketSurface(value: string | null | undefined): SurfaceBucket {
	if (!value) return 'unknown';
	const v = value.toLowerCase().trim();
	switch (v) {
		case 'paved':
		case 'asphalt':
		case 'concrete':
		case 'paving_stones':
		case 'sett':
		case 'cobblestone':
		case 'metal':
		case 'wood':
			return 'paved';
		case 'unpaved':
		case 'compacted':
			return 'unpaved';
		case 'gravel':
		case 'fine_gravel':
		case 'pebblestone':
			return 'gravel';
		case 'ground':
		case 'dirt':
		case 'earth':
		case 'grass':
		case 'mud':
		case 'sand':
			return 'ground';
		case 'rock':
		case 'scree':
		case 'stone':
			return 'rock';
		default:
			return 'unknown';
	}
}

/**
 * SAC scale buckets with a synthetic 'untagged' value for runs where the
 * OSM way has no sac_scale tag (the bulk of non-alpine terrain). Keeping
 * 'untagged' as a first-class bucket lets the renderer choose to color it
 * neutrally rather than hiding it.
 */
export type SacBucket = SacScale | 'untagged';

export function bucketSac(value: SacScale | null | undefined): SacBucket {
	return value ?? 'untagged';
}

let cachedPromise: Promise<TrailOsmTagsFile | null> | null = null;

/**
 * Loads the bundled OSM tag dataset (and, if configured, the remote variant).
 * Mirrors the seasonal-status loader pattern: remote first when
 * NEXT_PUBLIC_TRAIL_OSM_TAGS_URL is set, fallback to /trail-osm-tags.json on
 * any error. Result is cached for the lifetime of the page.
 */
export function loadTrailOsmTags(): Promise<TrailOsmTagsFile | null> {
	if (!cachedPromise) {
		cachedPromise = fetchTrailOsmTags();
	}
	return cachedPromise;
}

export function resetTrailOsmTagsCache(): void {
	cachedPromise = null;
}

async function fetchTrailOsmTags(): Promise<TrailOsmTagsFile | null> {
	const remoteUrl = process.env.NEXT_PUBLIC_TRAIL_OSM_TAGS_URL;
	if (remoteUrl && isSafeUrl(remoteUrl)) {
		try {
			const res = await fetch(remoteUrl);
			if (res.ok) return normalize((await res.json()) as Partial<TrailOsmTagsFile>);
		} catch {
			// fall through
		}
	}
	try {
		const res = await fetch('/trail-osm-tags.json');
		if (res.ok) return normalize((await res.json()) as Partial<TrailOsmTagsFile>);
	} catch {
		// ignore
	}
	return null;
}

/** Defensive bound to refuse remote payloads that exceed plausible run counts.
 *  A 2,200 km trail at fine OSM tagging produces at most ~10 k runs in practice. */
const MAX_RUNS = 50_000;

/** Defensive cap for any OSM tag string; bucket functions only consume known
 *  short values (e.g. "paved", "T3") and fall back to "unknown" / "untagged"
 *  for anything else, so longer strings are pure memory waste. */
const MAX_TAG_LEN = 64;

function isTagField(v: unknown): boolean {
	// Treat omitted (undefined) fields as null so a remote payload that drops
	// optional tags is accepted rather than rejecting the entire run.
	return v == null || (typeof v === 'string' && v.length <= MAX_TAG_LEN);
}

function isValidRun(r: unknown): r is TrailOsmTagRun {
	if (!r || typeof r !== 'object') return false;
	const o = r as Record<string, unknown>;
	return (
		Number.isFinite(o.fromKm) &&
		Number.isFinite(o.toKm) &&
		(o.fromKm as number) <= (o.toKm as number) &&
		isTagField(o.surface) &&
		isTagField(o.highway) &&
		isTagField(o.sac_scale) &&
		isTagField(o.mtb_scale)
	);
}

function normalize(raw: Partial<TrailOsmTagsFile>): TrailOsmTagsFile | null {
	if (!raw || typeof raw !== 'object') return null;
	if (!Array.isArray(raw.runs)) return null;
	if (raw.runs.length > MAX_RUNS) return null;
	if (!raw.runs.every(isValidRun)) return null;
	return {
		lastUpdated: raw.lastUpdated ?? '',
		totalKm: typeof raw.totalKm === 'number' ? raw.totalKm : 0,
		sampleStepM: raw.sampleStepM,
		runs: raw.runs,
	};
}

/**
 * Binary-search the run array for the run that contains the given km. Returns
 * null if km is outside every run (typically end-of-trail past the last run's
 * toKm, or before the first run starts).
 */
export function findRunAtKm(runs: TrailOsmTagRun[], km: number): TrailOsmTagRun | null {
	if (runs.length === 0) return null;
	let lo = 0;
	let hi = runs.length - 1;
	while (lo <= hi) {
		const mid = (lo + hi) >> 1;
		const r = runs[mid];
		if (km < r.fromKm) hi = mid - 1;
		else if (km > r.toKm) lo = mid + 1;
		else return r;
	}
	return null;
}
