import { isSafeUrl } from '@/lib/utils';
import type { TrailDirection } from '@/lib/types';

/**
 * Marked-trail junctions: OSM route relations (route=hiking/foot) that branch
 * off the CLDT, snapped to the trail polyline at their nearest-approach km.
 * Generated by `scripts/enrich-trail-junctions.ts` and served at
 * /data/trail-junctions.json.
 *
 * TEMPER FRAMING: each entry is "the marked trail that branches off here",
 * keyed on the OSM name / ref / osmc:symbol / network of the branching route
 * relation. It is NOT an authoritative HPS Registar lookup - HPS route numbers
 * are unreliable in OSM, so the UI credits OpenStreetMap and never presents a
 * ref as an official trail identifier.
 *
 * The bundled dataset ships EMPTY (like public/data/mine-areas.json) so the
 * whole feature stays dormant - no chip layer, no toggle, no data-book rows -
 * until a maintainer runs `npm run enrich-junctions` and commits real data.
 */

export interface TrailJunction {
	/** SOBO km of the CLDT point where the marked trail comes nearest. */
	trailKm: number;
	/** OSM name of the branching route relation. */
	name?: string;
	/** OSM ref (often an HPS number; unreliable in OSM). */
	ref?: string;
	/** OSM network tag (iwn / nwn / rwn / lwn). */
	network?: string;
	/** OSM osmc:symbol tag; its leading token is a waymark colour. */
	osmcSymbol?: string;
	/** Optional precomputed CSS colour; runtime falls back to osmcSymbol. */
	markColor?: string;
	/** Great-circle bearing (deg, 0-360 CW from north) the trail heads off the CLDT. */
	offBearingDeg?: number;
	/** 'crosses' when it shares the junction point, 'near' when only within snap radius. */
	proximity?: string;
}

export interface TrailJunctionsFile {
	lastUpdated: string;
	totalKm: number;
	source: string;
	junctions: TrailJunction[];
}

/** Neutral chip colour used when osmc:symbol has no usable leading colour token. */
export const TRAIL_JUNCTION_NEUTRAL_COLOR = '#6b7280';

/** Defensive bound: even a densely mapped 2,200 km corridor yields far fewer
 *  route relations than this, so a larger payload is treated as corrupt. */
const MAX_JUNCTIONS = 20_000;

/** Defensive cap for any OSM tag string kept from a remote payload. osmc:symbol
 *  can be long, so allow more room than the other short tags. */
const MAX_TAG_LEN = 200;

/** Named CSS colours OSM's osmc:symbol vocabulary uses for its leading token,
 *  mapped to hex so the chip renders consistently in light and dark themes.
 *  Anything outside this set falls back to the neutral colour. */
const OSMC_COLOR_HEX: Record<string, string> = {
	red: '#dc2626',
	blue: '#2563eb',
	green: '#16a34a',
	yellow: '#eab308',
	orange: '#ea580c',
	purple: '#9333ea',
	violet: '#7c3aed',
	white: '#e5e7eb',
	black: '#111827',
	brown: '#92400e',
	gray: '#6b7280',
	grey: '#6b7280',
};

/**
 * Extracts a CSS colour from a free-form OSM `osmc:symbol` value. The tag is a
 * colon-delimited waymark description whose FIRST token is the background /
 * primary colour (e.g. `red:red:white_bar` or `blue:white:blue_dot`). We take
 * only that leading colour token and map it to hex; anything unrecognised (or a
 * missing tag) falls back to the neutral colour so the chip always renders.
 */
export function parseOsmcSymbolColor(osmcSymbol?: string | null): string {
	if (!osmcSymbol || typeof osmcSymbol !== 'string') return TRAIL_JUNCTION_NEUTRAL_COLOR;
	const leading = osmcSymbol.split(':', 1)[0]?.trim().toLowerCase();
	if (!leading) return TRAIL_JUNCTION_NEUTRAL_COLOR;
	return OSMC_COLOR_HEX[leading] ?? TRAIL_JUNCTION_NEUTRAL_COLOR;
}

/** Strict CSS-colour allowlist for a precomputed markColor: a hex literal
 *  (#RGB / #RGBA / #RRGGBB / #RRGGBBAA) or one of the known OSM waymark colour
 *  names. markColor reaches a raw-HTML style attribute in the chip DivIcon, so
 *  it is validated here at the source: anything outside this allowlist can never
 *  carry markup and is rejected in favour of the osmc:symbol / neutral fallback. */
const HEX_COLOR_RE = /^#(?:[0-9a-f]{3}|[0-9a-f]{4}|[0-9a-f]{6}|[0-9a-f]{8})$/i;

function sanitizeMarkColor(markColor: string): string | null {
	const trimmed = markColor.trim();
	if (HEX_COLOR_RE.test(trimmed)) return trimmed;
	const hex = OSMC_COLOR_HEX[trimmed.toLowerCase()];
	return hex ?? null;
}

/** Resolves the chip colour for a junction: a valid explicit markColor wins,
 *  otherwise derive from osmc:symbol, otherwise the neutral colour. markColor is
 *  allowlist-validated (strict hex or a known colour name) so it can only ever
 *  return a safe colour token, never attacker-controlled markup. */
export function junctionColor(junction: TrailJunction): string {
	if (junction.markColor && typeof junction.markColor === 'string') {
		const safe = sanitizeMarkColor(junction.markColor);
		if (safe) return safe;
	}
	return parseOsmcSymbolColor(junction.osmcSymbol);
}

/** True once the bundled dataset actually carries junctions. The repo ships an
 *  empty file until `npm run enrich-junctions` is executed, so every UI surface
 *  gates on this and renders nothing while the feature is dormant. */
export function hasTrailJunctions(file: TrailJunctionsFile | null): file is TrailJunctionsFile {
	return !!file && file.junctions.length > 0;
}

function clampTag(v: unknown): string | undefined {
	if (typeof v !== 'string') return undefined;
	const trimmed = v.trim();
	if (!trimmed) return undefined;
	return trimmed.slice(0, MAX_TAG_LEN);
}

function normalizeJunction(raw: unknown): TrailJunction | null {
	if (!raw || typeof raw !== 'object') return null;
	const o = raw as Record<string, unknown>;
	if (!Number.isFinite(o.trailKm) || (o.trailKm as number) < 0) return null;
	const junction: TrailJunction = { trailKm: o.trailKm as number };
	const name = clampTag(o.name);
	if (name) junction.name = name;
	const ref = clampTag(o.ref);
	if (ref) junction.ref = ref;
	const network = clampTag(o.network);
	if (network) junction.network = network;
	const osmcSymbol = clampTag(o.osmcSymbol);
	if (osmcSymbol) junction.osmcSymbol = osmcSymbol;
	const markColor = clampTag(o.markColor);
	if (markColor) junction.markColor = markColor;
	if (Number.isFinite(o.offBearingDeg)) {
		// Wrap into [0, 360) so a hand-edited value can never rotate a chip glyph past a full turn.
		junction.offBearingDeg = (((o.offBearingDeg as number) % 360) + 360) % 360;
	}
	const proximity = clampTag(o.proximity);
	if (proximity) junction.proximity = proximity;
	return junction;
}

/** Validate + sanitise a raw payload (remote or bundled) into a
 *  TrailJunctionsFile, dropping malformed junctions and rejecting oversized or
 *  structurally invalid files. Returns null when the file cannot be trusted. */
export function normalize(raw: Partial<TrailJunctionsFile> | null | undefined): TrailJunctionsFile | null {
	if (!raw || typeof raw !== 'object') return null;
	if (!Array.isArray(raw.junctions)) return null;
	if (raw.junctions.length > MAX_JUNCTIONS) return null;
	const junctions: TrailJunction[] = [];
	for (const item of raw.junctions) {
		const j = normalizeJunction(item);
		if (j) junctions.push(j);
	}
	// Keep sorted by trailKm so ahead-lookups and stage filters can rely on order.
	junctions.sort((a, b) => a.trailKm - b.trailKm);
	return {
		lastUpdated: typeof raw.lastUpdated === 'string' ? raw.lastUpdated : '',
		totalKm: typeof raw.totalKm === 'number' ? raw.totalKm : 0,
		source: typeof raw.source === 'string' && raw.source.length > 0 ? raw.source : 'OpenStreetMap',
		junctions,
	};
}

/**
 * Loads the marked-trail junction dataset: the remote override
 * (NEXT_PUBLIC_TRAIL_JUNCTIONS_URL, when set and safe) first, then the bundled
 * /data/trail-junctions.json. Returns null on total failure so the layer simply
 * stays hidden. Mirrors loadTrailOsmTags / the mine-areas fetch.
 */
export async function loadTrailJunctions(): Promise<TrailJunctionsFile | null> {
	const remoteUrl = process.env.NEXT_PUBLIC_TRAIL_JUNCTIONS_URL;
	if (remoteUrl && isSafeUrl(remoteUrl)) {
		try {
			const res = await fetch(remoteUrl);
			if (res.ok) return normalize((await res.json()) as Partial<TrailJunctionsFile>);
		} catch {
			// fall through to the bundled copy
		}
	}
	try {
		const res = await fetch('/data/trail-junctions.json');
		if (res.ok) return normalize((await res.json()) as Partial<TrailJunctionsFile>);
	} catch {
		// ignore - the layer stays empty
	}
	return null;
}

export interface JunctionAhead {
	junction: TrailJunction;
	/** Distance ahead in the direction of travel, in km (>= 0). */
	aheadKm: number;
}

/**
 * Junctions ahead of `anchorSoboKm` within `horizonKm`, in the direction of
 * travel, sorted nearest-first. SOBO counts junctions at a higher SOBO km as
 * ahead; NOBO counts lower SOBO km as ahead. A junction exactly at the anchor
 * is included (aheadKm 0).
 */
export function junctionsAhead(
	junctions: TrailJunction[],
	anchorSoboKm: number,
	horizonKm: number,
	direction: TrailDirection,
): JunctionAhead[] {
	const out: JunctionAhead[] = [];
	for (const junction of junctions) {
		const aheadKm = direction === 'SOBO' ? junction.trailKm - anchorSoboKm : anchorSoboKm - junction.trailKm;
		if (aheadKm < 0 || aheadKm > horizonKm) continue;
		out.push({ junction, aheadKm });
	}
	out.sort((a, b) => a.aheadKm - b.aheadKm);
	return out;
}
