/**
 * Shared localization table for the trip-brief PDF and DOCX generators.
 * Both generators import LBL from here so label changes only need to be
 * made in one place. Emergency body text and any generator-specific
 * phrasing remain in each generator.
 */

import type { TripBrief, TripBriefDay } from '@/lib/trip-brief';
import { TrailDirection } from '@/lib/types';

export type TripBriefLocale = TripBrief['meta']['locale'];

/** Shared label strings used in both the PDF and DOCX generators.
 *
 *  Full Croatian / German diacritics are safe to use here: the PDF generator
 *  embeds a subsetted Noto Sans (see `trip-brief-fonts.ts`) covering Basic
 *  Latin, Latin-1 Supplement, and Latin Extended-A, and the DOCX path has
 *  always supported the full Unicode range. */
export const LBL = {
	en: {
		overview: 'Overview',
		totalDistance: 'Total distance',
		dayCount: 'Days',
		direction: 'Direction',
		gain: 'Elevation gain',
		loss: 'Elevation loss',
		eta: 'Walking time',
		pace: 'Pace',
		alerts: 'Alerts',
		pois: 'Places along the way',
		emergency: 'Emergency contacts',
		generated: 'Generated by CLDT Map at',
	},
	hr: {
		overview: 'Pregled',
		totalDistance: 'Ukupna udaljenost',
		dayCount: 'Broj dana',
		direction: 'Smjer',
		gain: 'Uspon',
		loss: 'Spust',
		eta: 'Vrijeme hodanja',
		pace: 'Brzina',
		alerts: 'Upozorenja',
		pois: 'Mjesta uz put',
		emergency: 'Hitne službe',
		generated: 'Generirano u CLDT karti',
	},
	de: {
		overview: 'Übersicht',
		totalDistance: 'Gesamtdistanz',
		dayCount: 'Tage',
		direction: 'Richtung',
		gain: 'Aufstieg',
		loss: 'Abstieg',
		eta: 'Gehzeit',
		pace: 'Tempo',
		alerts: 'Warnungen',
		pois: 'Orte am Weg',
		emergency: 'Notfallkontakte',
		generated: 'Erstellt mit CLDT Map am',
	},
	it: {
		overview: 'Panoramica',
		totalDistance: 'Distanza totale',
		dayCount: 'Giorni',
		direction: 'Direzione',
		gain: 'Dislivello positivo',
		loss: 'Dislivello negativo',
		eta: 'Tempo di cammino',
		pace: 'Andatura',
		alerts: 'Avvisi',
		pois: 'Luoghi lungo il percorso',
		emergency: 'Contatti di emergenza',
		generated: 'Generato da CLDT Map il',
	},
} as const;

/** PDF cover day-by-day list heading, localised. */
export const DAYS_HEADING = {
	en: 'Day-by-day',
	hr: 'Po danima',
	de: 'Tag für Tag',
	it: 'Giorno per giorno',
} as const;

/** PDF cover "+ N more places" footer label, localised. */
export const MORE_LABEL = {
	en: 'more places',
	hr: 'još mjesta',
	de: 'weitere Orte',
	it: 'altri luoghi',
} as const;

/** Direction descriptors used in the assembled trip overview narrative, e.g.
 *  "southbound (Ilok to Prevlaka)". */
export const NARRATIVE_DIRECTION = {
	en: { SOBO: 'southbound (Ilok to Prevlaka)', NOBO: 'northbound (Prevlaka to Ilok)' },
	hr: { SOBO: 'južno (Ilok prema Prevlaki)', NOBO: 'sjeverno (Prevlaka prema Iloku)' },
	de: { SOBO: 'südwärts (Ilok nach Prevlaka)', NOBO: 'nordwärts (Prevlaka nach Ilok)' },
	it: { SOBO: 'verso sud (Ilok verso Prevlaka)', NOBO: 'verso nord (Prevlaka verso Ilok)' },
} as const;

/** Day-narrative templates. `{day}`, `{totalDays}`, `{distanceLabel}`,
 *  `{gain}`, `{loss}`, and `{poiSentence}` are substituted by `formatDayNarrative`. */
const DAY_NARRATIVE_TEMPLATES = {
	en: 'Day {day} of {totalDays}: {distanceLabel}, +{gain} m / -{loss} m. {poiSentence}',
	hr: '{day}. dan od {totalDays}: {distanceLabel}, +{gain} m / -{loss} m. {poiSentence}',
	de: 'Tag {day} von {totalDays}: {distanceLabel}, +{gain} m / -{loss} m. {poiSentence}',
	it: 'Giorno {day} di {totalDays}: {distanceLabel}, +{gain} m / -{loss} m. {poiSentence}',
} as const;

/** Trailing sentence appended to the day narrative depending on whether the
 *  stage has at least one POI. */
const DAY_POI_SENTENCE = {
	en: { withPois: '{poiCount} places along the way.', empty: 'No notable places on this stage.' },
	hr: { withPois: '{poiCount} mjesta uz put.', empty: 'Nema posebnih mjesta uz ovu etapu.' },
	de: { withPois: '{poiCount} Orte am Weg.', empty: 'Keine besonderen Orte auf dieser Etappe.' },
	it: { withPois: '{poiCount} luoghi lungo il percorso.', empty: 'Nessun luogo notabile in questa tappa.' },
} as const;

/** Overview-narrative templates. `{totalDistanceLabel}`, `{dayCount}`,
 *  `{direction}`, and `{etaLabel}` are substituted by `formatOverviewNarrative`. */
const OVERVIEW_NARRATIVE_TEMPLATES = {
	en: 'The plan covers {totalDistanceLabel} across {dayCount} days {direction}. Estimated walking time: {etaLabel}.',
	hr: 'Plan obuhvaća {totalDistanceLabel} u {dayCount} dana {direction}. Procijenjeno vrijeme hodanja: {etaLabel}.',
	de: 'Der Plan umfasst {totalDistanceLabel} in {dayCount} Tagen {direction}. Geschätzte Gehzeit: {etaLabel}.',
	it: 'Il piano copre {totalDistanceLabel} in {dayCount} giorni {direction}. Tempo di cammino stimato: {etaLabel}.',
} as const;

/** Render the per-day narrative line for the trip brief. */
export function formatDayNarrative(args: {
	day: number;
	totalDays: number;
	distanceLabel: string;
	gainM: number;
	lossM: number;
	poiCount: number;
	locale: TripBriefLocale;
}): string {
	const { day, totalDays, distanceLabel, gainM, lossM, poiCount, locale } = args;
	const poiSentence =
		poiCount > 0
			? DAY_POI_SENTENCE[locale].withPois.replace('{poiCount}', String(poiCount))
			: DAY_POI_SENTENCE[locale].empty;
	return DAY_NARRATIVE_TEMPLATES[locale]
		.replace('{day}', String(day))
		.replace('{totalDays}', String(totalDays))
		.replace('{distanceLabel}', distanceLabel)
		.replace('{gain}', String(Math.round(gainM)))
		.replace('{loss}', String(Math.round(lossM)))
		.replace('{poiSentence}', poiSentence);
}

/** Render the trip-level overview narrative for the cover page. */
export function formatOverviewNarrative(args: {
	totalDistanceLabel: string;
	dayCount: number;
	direction: TrailDirection;
	locale: TripBriefLocale;
	etaLabel: string;
}): string {
	const { totalDistanceLabel, dayCount, direction, locale, etaLabel } = args;
	return OVERVIEW_NARRATIVE_TEMPLATES[locale]
		.replace('{totalDistanceLabel}', totalDistanceLabel)
		.replace('{dayCount}', String(dayCount))
		.replace('{direction}', NARRATIVE_DIRECTION[locale][direction])
		.replace('{etaLabel}', etaLabel);
}

/** Direction display string shared across PDF and DOCX. */
export function directionDisplay(d: TrailDirection, l: TripBriefLocale): string {
	const labels = {
		en: { SOBO: 'Southbound (Ilok - Prevlaka)', NOBO: 'Northbound (Prevlaka - Ilok)' },
		hr: { SOBO: 'Južno (Ilok - Prevlaka)', NOBO: 'Sjeverno (Prevlaka - Ilok)' },
		de: { SOBO: 'Südwärts (Ilok - Prevlaka)', NOBO: 'Nordwärts (Prevlaka - Ilok)' },
		it: { SOBO: 'Verso sud (Ilok - Prevlaka)', NOBO: 'Verso nord (Prevlaka - Ilok)' },
	};
	return labels[l][d];
}

/** Day header string (e.g. "Day 1 - km 0 to 25") shared across PDF and DOCX. */
export function dayHeader(day: TripBriefDay, l: TripBriefLocale, units: TripBrief['meta']['units']): string {
	const k0 = Math.round(day.directionStartKm);
	const k1 = Math.round(day.directionEndKm);
	const unit = units === 'imperial' ? 'mi' : 'km';
	const w = {
		en: `Day ${day.index + 1} - ${unit} ${k0} to ${k1}`,
		hr: `${day.index + 1}. dan - ${unit} ${k0} do ${k1}`,
		de: `Tag ${day.index + 1} - ${unit} ${k0} bis ${k1}`,
		it: `Giorno ${day.index + 1} - ${unit} ${k0} a ${k1}`,
	};
	return w[l];
}

/** Format a distance value for display in trip-brief documents. */
export function formatKmRound(km: number, units: TripBrief['meta']['units']): string {
	if (units === 'imperial') return `${(km * 0.621371).toFixed(1)} mi`;
	return `${km.toFixed(1)} km`;
}

/** Emergency back-page bullet lines, localised. Shared across the PDF and
 *  DOCX generators so a wording correction only needs to be made once. */
export const EMERGENCY_BODY = {
	en: [
		'Emergency: 112',
		'Mountain Rescue (HGSS): 112 (request HGSS)',
		'Always carry: water, headlamp, whistle, first-aid kit, GPS-enabled phone.',
		'In emergency: stay put if possible, mark location, contact rescue.',
		'In offline areas: SMS 112 with coordinates if voice fails.',
	],
	hr: [
		'Hitno: 112',
		'Gorska služba spašavanja (HGSS): 112 (zatraži HGSS)',
		'Uvijek nosi: vodu, čelnu svjetiljku, zviždaljku, prvu pomoć, mobitel s GPS-om.',
		'U hitnoj situaciji: ostani na mjestu ako možeš, označi poziciju, kontaktiraj spasioce.',
		'U područjima bez signala: SMS 112 s koordinatama ako poziv ne radi.',
	],
	de: [
		'Notruf: 112',
		'Bergrettung (HGSS): 112 (HGSS anfordern)',
		'Immer mitnehmen: Wasser, Stirnlampe, Trillerpfeife, Erste-Hilfe-Set, GPS-Telefon.',
		'Im Notfall: nach Möglichkeit am Ort bleiben, Position markieren, Rettung verständigen.',
		'In Offline-Gebieten: SMS an 112 mit Koordinaten, falls Anrufe nicht funktionieren.',
	],
	it: [
		'Emergenza: 112',
		'Soccorso alpino (HGSS): 112 (chiedere HGSS)',
		'Portare sempre: acqua, lampada frontale, fischietto, kit di primo soccorso, telefono con GPS.',
		'In emergenza: se possibile restare sul posto, segnalare la posizione, chiamare i soccorsi.',
		'Zone senza copertura: SMS al 112 con le coordinate se le chiamate non funzionano.',
	],
} as const;

/** Today's date as an ISO 8601 string (YYYY-MM-DD). */
export function todayIsoDate(): string {
	const d = new Date();
	const y = d.getFullYear();
	const m = String(d.getMonth() + 1).padStart(2, '0');
	const day = String(d.getDate()).padStart(2, '0');
	return `${y}-${m}-${day}`;
}

export { formatIsoDate as formatGeneratedAt } from './date-format';
