import type { StoreState, MapStoreState, TrailDirection, UnitSystem } from './types';
import { BaseMapProvider } from '../services/map-service';
import { INITIAL_TRAIL_STATE } from './trail-slice';

/**
 * Returns an object matching StoreState with default values and no-op functions for SSR.
 */
export function createStoreStub(): StoreState {
	return {
		userLocation: null,
		isLocating: false,
		userLocationInitialized: false,
		initialLocationSet: false,
		permissionStatus: null,
		showPermissionNotification: false,
		locationError: null,
		showUserMarker: true,
		...INITIAL_TRAIL_STATE,
		direction: 'SOBO' as TrailDirection,
		showBoundary: false,
		showTileBoundary: false,
		units: 'metric' as UnitSystem,
		mapMountTime: null,
		setUserLocation: () => {},
		setIsLocating: () => {},
		setUserLocationInitialized: () => {},
		setInitialLocationSet: () => {},
		setPermissionStatus: () => {},
		setShowPermissionNotification: () => {},
		setLocationError: () => {},
		setShowUserMarker: () => {},
		handleLocationUpdate: () => {},
		togglePermissionNotification: () => {},
		getCurrentLocation: async () => {},
		initLocationService: () => {},
		requestLocationPermission: async () => {},
		setTrailPoints: () => {},
		setEnhancedTrailPoints: () => {},
		setHighlightedTrailPoint: () => {},
		setBoundaryInitialized: () => {},
		setGpxLoaded: () => {},
		setGpxLoadFailed: () => {},
		setClosestPointCalculated: () => {},
		setShowClosestPointLine: () => {},
		setClosestPoint: () => {},
		setTrailMetadata: () => {},
		setRawGpxData: () => {},
		setGpxElevationPoints: () => {},
		setDirection: () => {},
		calculateClosestPoint: () => {},
		forceCalculateClosestPointFromLocation: () => {},
		broadcastDirectionChange: () => {},
		processTrailData: () => {},
		highlightTrailPosition: () => {},
		clearTrailHighlight: () => {},
		setTooltipPinnedFromShare: () => {},
		requestRawGpxData: () => null,
		findTrailPointByDistance: () => null,
		findTrailPointByCoordinates: () => null,
		setShowBoundary: () => {},
		setShowTileBoundary: () => {},
		setUnits: () => {},
		setMapMountTime: () => {},
		broadcastUnitsChange: () => {},
	};
}

const noop = (): void => {};
const noopAsyncLocation = async (): Promise<{ lat: number; lng: number }> => ({ lat: 0, lng: 0 });
const noopAsyncVoid = async (): Promise<void> => {};
const noopNull = (): string | null => null;

/**
 * Returns an object matching MapStoreState with default values and no-op functions for SSR.
 */
export function createMapStoreStub(): MapStoreState {
	return {
		selectedTrail: null,
		setSelectedTrail: noop,
		trailData: null,
		setTrailData: noop,
		startPoint: null,
		endPoint: null,
		totalDistance: 0,
		elevationGain: 0,
		elevationLoss: 0,
		rawGpxData: null,
		setRawGpxData: noop,
		gpxElevationPoints: [],
		setGpxElevationPoints: noop,
		gpxLoaded: false,
		setGpxLoaded: noop,
		gpxLoadFailed: false,
		setGpxLoadFailed: noop,
		reloadTrailRequested: 0,
		setReloadTrailRequested: noop,
		units: 'metric' as UnitSystem,
		setUnits: noop,
		direction: 'SOBO' as TrailDirection,
		setDirection: noop,
		showBoundary: false,
		setShowBoundary: noop,
		showTileBoundary: false,
		setShowTileBoundary: noop,
		isRulerEnabled: false,
		setRulerEnabled: noop,
		userLocation: null,
		isLocating: false,
		permissionStatus: null,
		locationError: null,
		showUserMarker: true,
		distancePrecision: 2,
		setDistancePrecision: noop,
		setUserLocation: noop,
		setIsLocating: noop,
		setPermissionStatus: noop,
		setLocationError: noop,
		getCurrentLocation: noopAsyncLocation,
		initLocationService: noop,
		requestLocationPermission: noopAsyncVoid,
		setShowUserMarker: noop,
		fakeUserLocationEnabled: false,
		setFakeUserLocationEnabled: noop,
		setFakeUserLocation: noop,
		setFakeUserLocationOnTrail: noopAsyncVoid,
		darkMode: false,
		setDarkMode: noop,
		batterySaverMode: false,
		setBatterySaverMode: noop,
		largeTouchTargets: false,
		setLargeTouchTargets: noop,
		showSections: false,
		setShowSections: noop,
		baseMapProvider: BaseMapProvider.OPEN_STREET_MAP,
		setBaseMapProvider: noop,
		isMapFullscreen: false,
		setMapFullscreen: noop,
		requestRawGpxData: noopNull,
		processTrailData: () => {},
	};
}
