import type { StoreState, MapStoreState } from './types';
import { BaseMapProvider } from '../services/map-service';
import { INITIAL_TRAIL_STATE } from './trail-slice';
import { DEFAULT_POI_TYPES } from '../poi-types';

/**
 * Returns an object matching StoreState with default values and no-op functions for SSR.
 */
export function createStoreStub(): StoreState {
	return {
		userLocation: null,
		isLocating: false,
		initialLocationSet: false,
		permissionStatus: null,
		locationError: null,
		showUserMarker: true,
		...INITIAL_TRAIL_STATE,
		direction: 'SOBO',
		showBoundary: false,
		showTileBoundary: false,
		units: 'metric',
		mapMountTime: null,
		setUserLocation: () => {},
		setIsLocating: () => {},
		setPermissionStatus: () => {},
		setLocationError: () => {},
		setShowUserMarker: () => {},
		handleLocationUpdate: () => {},
		getCurrentLocation: async () => {},
		initLocationService: () => {},
		requestLocationPermission: async () => {},
		setTrailPoints: () => {},
		setEnhancedTrailPoints: () => {},
		setHighlightedTrailPoint: () => {},
		setBoundaryInitialized: () => {},
		setGpxLoaded: () => {},
		setGpxLoadFailed: () => {},
		setClosestPointCalculated: () => {},
		setShowClosestPointLine: () => {},
		setClosestPoint: () => {},
		setTrailMetadata: () => {},
		setRawGpxData: () => {},
		setGpxElevationPoints: () => {},
		setDirection: () => {},
		calculateClosestPoint: () => {},
		forceCalculateClosestPointFromLocation: () => {},
		broadcastDirectionChange: () => {},
		processTrailData: () => {},
		applyComputedTrailData: () => {},
		highlightTrailPosition: () => {},
		clearTrailHighlight: () => {},
		setTooltipPinnedFromShare: () => {},
		requestRawGpxData: () => null,
		findTrailPointByDistance: () => null,
		findTrailPointByCoordinates: () => null,
		setShowBoundary: () => {},
		setShowTileBoundary: () => {},
		setUnits: () => {},
		setMapMountTime: () => {},
		broadcastUnitsChange: () => {},
	};
}

const noop = (): void => {};
const noopAsyncLocation = async (): Promise<{ lat: number; lng: number }> => ({ lat: 0, lng: 0 });
const noopAsyncVoid = async (): Promise<void> => {};
const noopNull = (): string | null => null;

/**
 * Returns an object matching MapStoreState with default values and no-op functions for SSR.
 */
export function createMapStoreStub(): MapStoreState {
	return {
		selectedTrail: null,
		setSelectedTrail: noop,
		trailData: null,
		setTrailData: noop,
		startPoint: null,
		endPoint: null,
		totalDistance: 0,
		elevationGain: 0,
		elevationLoss: 0,
		rawGpxData: null,
		setRawGpxData: noop,
		gpxElevationPoints: [],
		setGpxElevationPoints: noop,
		gpxLoaded: false,
		setGpxLoaded: noop,
		gpxLoadFailed: false,
		setGpxLoadFailed: noop,
		reloadTrailRequested: 0,
		setReloadTrailRequested: noop,
		units: 'metric',
		setUnits: noop,
		direction: 'SOBO',
		setDirection: noop,
		showBoundary: false,
		setShowBoundary: noop,
		showTileBoundary: false,
		setShowTileBoundary: noop,
		isRulerEnabled: false,
		setRulerEnabled: noop,
		showRadarOverlay: false,
		setShowRadarOverlay: noop,
		radarFrames: [],
		setRadarFrames: noop,
		radarFrameIndex: 0,
		setRadarFrameIndex: noop,
		radarPlaying: false,
		setRadarPlaying: noop,
		rulerRange: null,
		setRulerRange: noop,
		userLocation: null,
		isLocating: false,
		permissionStatus: null,
		locationError: null,
		showUserMarker: true,
		distancePrecision: 2,
		setDistancePrecision: noop,
		setUserLocation: noop,
		setIsLocating: noop,
		setPermissionStatus: noop,
		setLocationError: noop,
		getCurrentLocation: noopAsyncLocation,
		initLocationService: noop,
		requestLocationPermission: noopAsyncVoid,
		setShowUserMarker: noop,
		fakeUserLocationEnabled: false,
		setFakeUserLocationEnabled: noop,
		setFakeUserLocation: noop,
		setFakeUserLocationOnTrail: noopAsyncVoid,
		darkMode: false,
		setDarkMode: noop,
		batterySaverMode: false,
		compassEnabled: false,
		setCompassEnabled: noop,
		keepScreenOn: false,
		setKeepScreenOn: noop,
		offRouteAlertEnabled: false,
		setOffRouteAlertEnabled: noop,
		setBatterySaverMode: noop,
		largeTouchTargets: false,
		setLargeTouchTargets: noop,
		showSections: false,
		setShowSections: noop,
		gradeTintedTrail: false,
		setGradeTintedTrail: noop,
		surfaceColoured: false,
		setSurfaceColoured: noop,
		sacColoured: false,
		setSacColoured: noop,
		showDistanceMarkers: false,
		setShowDistanceMarkers: noop,
		baseMapProvider: BaseMapProvider.OPEN_STREET_MAP,
		setBaseMapProvider: noop,
		isMapFullscreen: false,
		setMapFullscreen: noop,
		openPanel: null,
		setOpenPanel: noop,
		togglePanel: noop,
		closePanel: noop,
		requestRawGpxData: noopNull,
		processTrailData: () => {},

		isOffline: false,
		setIsOffline: noop,
		initOfflineDetection: noop,
		tileCacheDownloading: false,
		tileCacheDone: 0,
		tileCacheTotal: 0,
		tileCacheError: null,
		tileCacheMeta: null,
		autoSync: false,
		predictivePrecache: false,
		poiPrefetchVersion: 0,
		poiPrefetchSkipped: null,
		startTileDownload: noopAsyncVoid,
		cancelTileDownload: noop,
		clearTileCacheForProvider: noopAsyncVoid,
		loadTileCacheMeta: noopAsyncVoid,
		setAutoSync: noop,
		setPredictivePrecache: noop,
		maybeRunPredictivePrecache: noopAsyncVoid,
		handleQuotaExceeded: noop,
		showStaleCacheNotification: false,
		setStaleCacheNotification: noop,
		initStaleCacheCheck: noopAsyncVoid,
		pwaInstallTrigger: null,
		clearPwaInstallTrigger: noop,
		tileDownloadCompleteToast: false,
		clearTileDownloadCompleteToast: noop,
		walkingPaceKmh: 4,
		setWalkingPaceKmh: noop,
		packBaseWeightKg: null,
		setPackBaseWeightKg: noop,
		waterConsumptionLph: 0.6,
		setWaterConsumptionLph: noop,
		foodConsumptionKgPerDay: 0.6,
		setFoodConsumptionKgPerDay: noop,
		packEtaAdjust: false,
		setPackEtaAdjust: noop,
		packGearList: null,
		setPackGearList: noop,
		pushAlertsEnabled: false,
		setPushAlertsEnabled: noop,
		waymarkedTrailsOverlay: false,
		setWaymarkedTrailsOverlay: noop,
		shareShortLinks: true,
		setShareShortLinks: noop,
		shareCopyToast: null,
		showShareCopyToast: noop,
		clearShareCopyToast: noop,
		userWaypoints: [],
		addUserWaypoint: noop,
		updateUserWaypoint: noop,
		removeUserWaypoint: noop,
		pendingOpenWaypointId: null,
		requestOpenWaypoint: noop,
		clearPendingOpenWaypoint: noop,
		lastWaypointCategory: 'generic',
		setLastWaypointCategory: noop,
		hiddenWaypointCategories: new Set(),
		toggleWaypointCategoryOnMap: noop,
		setHiddenWaypointCategories: noop,
		journalEntries: [],
		addJournalEntry: noop,
		updateJournalEntry: noop,
		removeJournalEntry: noop,
		gradeAdjustedEta: true,
		setGradeAdjustedEta: noop,
		sunsetProjection: false,
		setSunsetProjection: noop,
		stagePlan: null,
		setStagePlan: noop,
		clearStagePlan: noop,
		importedTracks: [],
		addImportedTrack: noop,
		removeImportedTrack: noopAsyncVoid,
		setImportedTracks: noop,
		updateImportedTrack: noop,
		progressTrackIds: [],
		addProgressTrackId: noop,
		removeProgressTrackId: noop,
		loadImportedTracksFromStorage: noopAsyncVoid,
		hoveredImportedTrackId: null,
		setHoveredImportedTrackId: noop,

		severeWeatherLayer: false,
		completedIntervals: [],
		markCompleted: () => {},
		unmarkCompleted: () => {},
		clearCompletion: () => {},
		completionAutoTrack: true,
		setCompletionAutoTrack: () => {},
		showCompletionOverlay: true,
		setShowCompletionOverlay: () => {},
		progressPreviewTrackId: null,
		progressPreviewIntervals: [],
		setProgressPreview: () => {},
		showUpNext: true,
		setShowUpNext: () => {},
		aheadHorizonKm: 50,
		setAheadHorizonKm: () => {},
		pendingPoiListSort: null,
		requestPoiListAhead: () => {},
		clearPendingPoiListSort: () => {},
		walkSim: null,
		setWalkSim: () => {},
		demoModeActive: false,
		demoPersistSnapshot: null,
		enterDemoMode: () => {},
		mineAreasEnabled: true,
		setMineAreasEnabled: () => {},
		mineAreasFile: null,
		setMineAreasFile: () => {},
		setSevereWeatherLayer: noop,
		severeWeatherData: null,
		setSevereWeatherData: noop,

		trailOsmTagsFile: null,
		setTrailOsmTagsFile: noop,

		poisFile: null,
		setPoisFile: noop,
		poisLayerEnabled: false,
		setPoisLayerEnabled: noop,
		poiDisclaimerDismissedAt: null,
		setPoiDisclaimerDismissedAt: noop,
		enabledPoiTypes: new Set(DEFAULT_POI_TYPES),
		setEnabledPoiTypes: noop,
		togglePoiType: noop,
		enabledPoiTags: new Set<string>(),
		setEnabledPoiTags: noop,
		togglePoiTag: noop,
		clearPoiTags: noop,
		includeRemotePois: false,
		setIncludeRemotePois: noop,
		poiFiltersUserModified: false,
		resetPoiFiltersToDefaults: noop,
		starredPoiIds: new Set<string>(),
		toggleStarredPoi: noop,
		clearStarredPois: noop,
		pendingOpenPoiId: null,
		requestOpenPoi: noop,
		clearPendingOpenPoi: noop,
		lightboxImages: null,
		lightboxIndex: 0,
		openLightbox: noop,
		closeLightbox: noop,
		setLightboxIndex: noop,

		seasonalStatusFile: null,
		setSeasonalStatusFile: noop,
		seasonalStatusEntries: [],
		seasonalStatusLayerEnabled: false,
		seasonalStatusLayerUserToggled: false,
		setSeasonalStatusLayerEnabled: noop,
		seasonalStatusModalEntry: null,
		setSeasonalStatusModalEntry: noop,
		seasonalStatusHoveredEntryId: null,
		setSeasonalStatusHoveredEntryId: noop,
	};
}
